spring.application.name=spring-learning
vnsms.api-key=1234567890
vnsms.sender-id=VNSMS
spring.datasource.url=jdbc:mysql://localhost:3306/quan_ly_kho
spring.datasource.username=root
spring.datasource.password=kha512020
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA and Hibernate properties (optional, good for development)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# It is recommended to set open-in-view to false unless you have a specific reason
spring.jpa.open-in-view=false 